<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-22T07:51:11Z" name="Suite" finished-at="2024-08-22T07:51:27Z" duration-ms="15910">
    <groups>
    </groups>
    <test started-at="2024-08-22T07:51:11Z" name="Test1" finished-at="2024-08-22T07:51:19Z" duration-ms="7884">
      <class name="package1.tc1">
        <test-method signature="f()[pri:0, instance:[tc1 passed=0 failed=0 skipped=0]]" started-at="2024-08-22T13:21:11Z" name="f" finished-at="2024-08-22T13:21:19Z" duration-ms="7660" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Demo Web Shop] but found [Demo Web Shops]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Demo Web Shop] but found [Demo Web Shops]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at package1.tc1.f(tc1.java:19)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
      </class> <!-- package1.tc1 -->
    </test> <!-- Test1 -->
    <test started-at="2024-08-22T07:51:19Z" name="Test2" finished-at="2024-08-22T07:51:27Z" duration-ms="7975">
      <class name="package1.tc2">
        <test-method signature="f()[pri:0, instance:[tc2 passed=0 failed=0 skipped=0]]" started-at="2024-08-22T13:21:19Z" name="f" finished-at="2024-08-22T13:21:27Z" duration-ms="7973" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
      </class> <!-- package1.tc2 -->
    </test> <!-- Test2 -->
  </suite> <!-- Suite -->
</testng-results>
