<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-TIC5DM4" name="com.App.Testcases.testrunner" tests="2" failures="1" timestamp="2024-08-26T11:59:35 IST" time="30.416" errors="0">
  <testcase name="runScenario" time="14.182" classname="com.App.Testcases.testrunner"/>
  <system-out/>
  <testcase name="runScenario" time="16.234" classname="com.App.Testcases.testrunner">
    <failure type="java.lang.AssertionError" message="expected [https://demowebshop.tricentis.com/login] but found [https://demowebshop.tricentis.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://demowebshop.tricentis.com/login] but found [https://demowebshop.tricentis.com/]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.App.Testcases.InvalidTest.he_enters_the_in_valid_details(InvalidTest.java:31)
at âœ½.he enters the in valid details(file:///C:/Users/Administrator/eclipse-workspace/CucumberDemoWeb/src/test/resources/features/back.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- com.App.Testcases.testrunner -->
